test-obj-y+=test_scale_angle.o
test-obj-y+=test_mem_store.o
test-obj-y+=test_network_shell.o
test-obj-y+=face_test.o
test-obj-y+=test_detect.o
test-obj-y+=test_align.o
test-obj-y+=test_feature.o
TEST_LIBS+=-lpthread
